### ISSUE TITLE
HTTP API errors silently fail

### ISSUE THREAD

**Issue by MauriceSprague** [DevoInc/python-sdk#58]
HTTP API errors when performing queries on the V2 api return an empty string.  It would be preferable if an exception was raised, or some actionable data was returned.

This has been verified with both HTTP 404 and 503 return codes.  The problem can be reproduced by performing an API request with invalid credentials, or an invalid URI path.

**Comment by Worvast** [comment]
Hi Maurice, yes, before version 2.2.1 most errors were silenced. After that version you can check if what it returns is an error or not, but I think it has not been a perfect execution, so it is preparing a new version (Major) that will have any problem with a raise DevoClientException, that will have the same structure for all the errors in the client, and that can be controlled with one 'except DevoClientException:'

As it is a change that involves making a Major version, it may be delayed a few weeks since I am doing a full review of all code, for search problems that may involve a version break and fix them too.

**Comment by Worvast** [comment]
Sorry for delay Maurice. With the new version 3.0 errors now all errors should be displayed correctly, homogeneously and without hiding information either in the SDK code or in the http responses.  If you have any problems, still let me know, if there are no more problems I will close the issue next week.

Again, I feel that it has taken so long to solve the problem.
